on:
 workflow_dispatch:
  inputs:
   chosen-os:
    required: true
    type: choice
    options:
    - ubuntu
    - macOS

jobs:
 test:
    runs-on: [self-hosted, "${{ inputs.chosen-os }}"]
    steps:
    - run: echo Hello World!
